# Generated by Django 5.1 on 2026-08-28 12:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='対戦部屋', max_length=50)),
                ('board_size', models.IntegerField(default=9)),
                ('fences_per_player', models.IntegerField(default=10)),
                ('current_turn', models.IntegerField(default=1)),
                ('winner', models.IntegerField(blank=True, null=True)),
                ('p1_pos', models.JSONField(default=dict)),
                ('p2_pos', models.JSONField(default=dict)),
                ('p1_fences_left', models.IntegerField(default=10)),
                ('p2_fences_left', models.IntegerField(default=10)),
                ('placed_fences', models.JSONField(default=list)),
            ],
        ),
    ]
