# Generated by Django 5.1 on 2025-12-19 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Xmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepting', models.BooleanField(default=False)),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_Xmas.question')),
            ],
        ),
    ]
