# Generated by Django 5.1 on 2025-12-19 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Xmas', '0002_quizstate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentQuestion',
        ),
    ]
