# Generated by Django 5.1 on 2025-12-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Xmas', '0003_delete_currentquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
