# Generated by Django 5.1 on 2025-12-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Xmas', '0004_question_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizstate',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
