# Generated by Django 5.1 on 2025-12-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Xmas', '0005_quizstate_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizstate',
            name='show_answer',
            field=models.BooleanField(default=False),
        ),
    ]
