# Generated by Django 5.1 on 2025-12-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Xmas', '0007_player_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, default='links/dafault.jpg', null=True, upload_to='xmas/links/')),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
    ]
