# Generated by Django 5.1 on 2025-12-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Xmas', '0008_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surprise', models.BooleanField()),
            ],
        ),
    ]
