# Generated by Django 4.1 on 2024-01-23 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('is_drawn', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('s_player', models.IntegerField(default=4)),
                ('s_one_image', models.IntegerField(default=3)),
                ('s_set_image', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Select_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_drawn', models.BooleanField(default=False)),
                ('get_player', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_dareyaomae.player')),
                ('image_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dareyaomae.image_card')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dareyaomae.room'),
        ),
        migrations.AddField(
            model_name='image_card',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dareyaomae.player'),
        ),
        migrations.AddField(
            model_name='image_card',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dareyaomae.room'),
        ),
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_card', models.ManyToManyField(to='app_dareyaomae.select_card')),
                ('players', models.ManyToManyField(to='app_dareyaomae.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dareyaomae.room')),
            ],
        ),
    ]
