# Generated by Django 4.1 on 2024-01-23 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dareyaomae', '0003_alter_select_card_get_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='select_card',
            name='get_player',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_dareyaomae.player'),
        ),
    ]
