# Generated by Django 4.1 on 2024-01-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dareyaomae', '0004_alter_select_card_get_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedata',
            name='image_card',
        ),
        migrations.AddField(
            model_name='select_card',
            name='game_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_dareyaomae.gamedata'),
            preserve_default=False,
        ),
    ]
