# Generated by Django 4.1 on 2024-01-23 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dareyaomae', '0006_remove_select_card_game_data_delete_gamedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='select_card',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_dareyaomae.room'),
            preserve_default=False,
        ),
    ]
