# Generated by Django 4.1 on 2024-01-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dareyaomae', '0008_alter_select_card_get_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_card',
            name='card_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
