# Generated by Django 4.1 on 2024-01-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dareyaomae', '0010_image_card_use_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='s_dupe',
            field=models.IntegerField(default=5),
        ),
    ]
