# Generated by Django 4.1 on 2024-03-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dareyaomae', '0011_room_s_dupe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='select_card',
            name='get_player',
        ),
        migrations.AddField(
            model_name='select_card',
            name='get_player',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='app_dareyaomae.player'),
        ),
    ]
