# Generated by Django 4.1 on 2024-04-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dareyaomae', '0012_remove_select_card_get_player_select_card_get_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='select_card',
            name='get_player',
            field=models.ManyToManyField(blank=True, default=None, to='app_dareyaomae.player'),
        ),
    ]
