# Generated by Django 5.1 on 2025-02-02 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dareyaomae', '0013_alter_select_card_get_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='select_card',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dareyaomae.room'),
        ),
    ]
