# Generated by Django 5.1 on 2026-08-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('tv', 'テレビ'), ('light', 'ライト'), ('aircon', 'エアコン'), ('remote', 'リモコン')], default='remote', max_length=20)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=4)),
                ('height', models.IntegerField(default=4)),
            ],
        ),
    ]
