# Generated by Django 5.1 on 2026-08-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smarthome', '0003_card_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='sub_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='parameter',
            field=models.CharField(default='default', max_length=500),
        ),
    ]
