# Generated by Django 5.1 on 2026-08-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_smarthome', '0005_device_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='features',
        ),
    ]
