# Generated by Django 5.1 on 2026-08-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smarthome', '0006_remove_device_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='features',
            field=models.JSONField(blank=True, default=list, verbose_name='対応機能'),
        ),
    ]
