# Generated by Django 5.1 on 2026-08-23 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smarthome', '0007_device_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='操作内容')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='詳細データ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作日時')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='app_smarthome.device', verbose_name='デバイス')),
            ],
            options={
                'verbose_name': '操作履歴',
                'verbose_name_plural': '操作履歴',
                'ordering': ['-created_at'],
            },
        ),
    ]
