# Generated by Django 5.1 on 2026-08-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smarthome', '0008_operationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='command_type',
            field=models.CharField(choices=[('command', 'command'), ('customize', 'customize')], default='command', max_length=20),
            preserve_default=False,
        ),
    ]
