# Generated by Django 5.1 on 2026-08-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smarthome', '0009_command_command_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('hub', 'ハブ'), ('light', 'ライト'), ('light_detail', 'ライト詳細付き'), ('concent', 'コンセント'), ('tv', 'テレビ'), ('aircon', 'エアコン'), ('PC', 'パソコン'), ('remote', 'リモコン')], max_length=20),
        ),
    ]
