# Generated by Django 5.1 on 2026-09-12 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smarthome', '0010_alter_device_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPowerConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='記録日')),
                ('power_kwh', models.FloatField(verbose_name='消費電力量(kWh)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_records', to='app_smarthome.device')),
            ],
            options={
                'unique_together': {('device', 'date')},
            },
        ),
    ]
