# Generated by Django 5.1 on 2025-02-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('game01', models.BooleanField(default=False)),
                ('game02', models.BooleanField(default=False)),
                ('game03', models.BooleanField(default=False)),
                ('game04', models.BooleanField(default=False)),
                ('game05', models.BooleanField(default=False)),
                ('game06', models.BooleanField(default=False)),
            ],
        ),
    ]
