# Generated by Django 5.1 on 2025-02-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lover', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
