# Generated by Django 5.1 on 2025-02-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lover', '0002_alter_selection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
