# Generated by Django 5.1 on 2025-03-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lover', '0003_alter_selection_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='gamestart',
            field=models.BooleanField(default=False),
        ),
    ]
