# Generated by Django 5.1 on 2025-05-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lover', '0005_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('he_name', models.CharField(max_length=255)),
                ('he_image', models.ImageField(upload_to='lover/line/image')),
                ('she_name', models.CharField(max_length=255)),
                ('she_image', models.ImageField(upload_to='lover/line/image')),
                ('backgroundImage', models.ImageField(upload_to='lover/line/image')),
            ],
        ),
    ]
