# Generated by Django 5.1 on 2025-05-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lover', '0007_alter_line_backgroundimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='backgroundImage',
            field=models.ImageField(blank=True, null=True, upload_to='lover/line/image'),
        ),
    ]
