# Generated by Django 5.1 on 2025-02-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('interview_status', models.CharField(choices=[('none', 'なし'), ('explained', '説明会済'), ('interview_1', '1次面接'), ('interview_2', '2次面接'), ('interview_3', '3次面接'), ('interview_4', '4次面接'), ('interview_5', '5次面接'), ('final_interview', '最終面接'), ('offer', '内定'), ('rejected', '落ちた')], default='none', max_length=20)),
                ('resume_required', models.BooleanField(default=False)),
                ('resume_submitted', models.BooleanField(default=False)),
                ('aptitude_test_required', models.BooleanField(default=False)),
                ('aptitude_test_taken', models.BooleanField(default=False)),
                ('web_test_required', models.BooleanField(default=False)),
                ('web_test_taken', models.BooleanField(default=False)),
                ('memo', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
