# Generated by Django 5.1 on 2025-02-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='interview_status',
            field=models.CharField(choices=[('none', 'なし'), ('briefing', '説明会済'), ('interview_1', '1次面接'), ('interview_2', '2次面接'), ('interview_3', '3次面接'), ('interview_4', '4次面接'), ('interview_5', '5次面接'), ('final', '最終面接'), ('offer', '内定'), ('rejected', '落ちた')], default='none', max_length=20),
        ),
    ]
