# Generated by Django 5.1 on 2025-02-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_FamilyCar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('distance', models.FloatField()),
                ('fuel_amount', models.FloatField()),
                ('cost_per_liter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('fuel_efficiency', models.FloatField()),
                ('cost_per_liter', models.IntegerField()),
                ('gas_records', models.ManyToManyField(to='app_FamilyCar.gasrecord')),
            ],
        ),
        migrations.DeleteModel(
            name='DriveRecord',
        ),
    ]
