# Generated by Django 5.1 on 2025-02-08 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_FamilyCar', '0003_remove_gasrecord_cost_per_liter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyrecord',
            name='gas_records',
        ),
        migrations.AddField(
            model_name='gasrecord',
            name='monthly_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_FamilyCar.monthlyrecord'),
        ),
        migrations.AlterField(
            model_name='monthlyrecord',
            name='cost_per_liter',
            field=models.IntegerField(default=170),
        ),
        migrations.AlterField(
            model_name='monthlyrecord',
            name='fuel_efficiency',
            field=models.FloatField(default=8),
        ),
    ]
