# Generated by Django 5.1 on 2025-02-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_FamilyCar', '0005_monthlyrecord_is_check_monthlyrecord_is_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasrecord',
            name='image',
            field=models.ImageField(null=True, upload_to='FamilyCar/gasData'),
        ),
    ]
