# Generated by Django 5.1 on 2025-03-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_FamilyCar', '0006_gasrecord_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='FamilyCar/gasData'),
        ),
    ]
