# Generated by Django 5.1 on 2025-05-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_useractivitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivitylog',
            options={'verbose_name': 'ログ', 'verbose_name_plural': 'アクティビティログ'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
