# Generated by Django 5.1 on 2025-02-04 23:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_link_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='user',
        ),
        migrations.AddField(
            model_name='link',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='links', to=settings.AUTH_USER_MODEL),
        ),
    ]
