# Generated by Django 5.1 on 2025-02-08 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_link_rank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='links', to=settings.AUTH_USER_MODEL),
        ),
    ]
