# Generated by Django 5.1 on 2025-01-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('join_time', models.DateTimeField()),
                ('leave_time', models.DateTimeField(blank=True, null=True)),
                ('current_world', models.CharField(max_length=100)),
                ('last_death_world', models.CharField(max_length=100)),
                ('last_death_x', models.IntegerField()),
                ('last_death_y', models.IntegerField()),
                ('last_death_z', models.IntegerField()),
                ('image', models.ImageField(default='player_images/default_image.png', upload_to='player_images/')),
            ],
        ),
    ]
