# Generated by Django 5.1 on 2025-01-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_minecraft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdata',
            name='last_death_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='last_death_y',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='last_death_z',
            field=models.IntegerField(null=True),
        ),
    ]
