# Generated by Django 5.1 on 2025-01-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_minecraft', '0002_alter_playerdata_last_death_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdata',
            name='current_world',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='last_death_world',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
