# Generated by Django 5.1 on 2025-01-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_minecraft', '0003_alter_playerdata_current_world_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdata',
            name='current_world',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='last_death_world',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='last_death_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='last_death_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='last_death_z',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
