# Generated by Django 5.1 on 2025-02-08 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_minecraft', '0004_alter_playerdata_current_world_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdata',
            name='total_play_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
